on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]

name: SonarQube Scan

jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@master
      with:
        fetch-depth: 0  # Disabling shallow clone for improved reporting relevance
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
        projectKey: Github-Action-Scan
