name: SonarQube Scan

on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Disabling shallow clone for improved reporting relevance

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: your-sonarqube-host  # Replace with your SonarQube server URL
        login: your-sonarqube-token  # Replace with your SonarQube server token
        projectKey: Github-Action-Scan
        options: -X  # Enable full debug logging

# Add more steps or modify the existing ones based on your project's needs
